name: Build & Test Rust Project

# Triggers
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Environment variables (available to all jobs)
env:
  CARGO_TERM_COLOR: always

# Jobs composing the action workflow
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
